#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source /usr/share/doc/pkgfile/command-not-found.zsh
export EDITOR="/usr/bin/vim"
source $HOME/.aliases
eval $(/usr/bin/keychain --eval --agents ssh -Q --quiet ~/.ssh/id_rsa)

# Disable hostname completion
zstyle ':completion:*' hosts off

#autoload -U select-word-style
#select-word-style bash
